# Generated by Django 5.2.8 on 2025-11-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentcredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcredentials',
            name='student_email',
        ),
    ]
