# Generated by Django 5.2.8 on 2025-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_studentcredentials_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcredentials',
            name='branch_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='studentcredentials',
            name='branch_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
